# Generated by Django 5.0 on 2024-01-18 08:08

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_hotel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
