# Generated by Django 5.0 on 2024-02-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_alter_reservation_check_in_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
