# Generated by Django 4.2.2 on 2024-03-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_alter_reservation_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelimage',
            name='hotel_images',
            field=models.ImageField(null=True, upload_to='bookaroom/hotel_images/'),
        ),
    ]
